import './globals.css';
import NavBar from './components/nav-bar/NavBar';
import Footer from './components/footer/Footer';

export const metadata = {
  title: 'starbucks',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
