import './globals.css';
import NavBar from './components/NavBar';
import Footer from './components/footer/Footer';

export const metadata = {
  title: 'starbucks',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <NavBar/> */}
      <body>{children}</body>
      {/* <Footer/> */}
    </html>
  );
}
